use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize)]
pub struct Resident {
    pub id: Option<i32>,
    pub prefix: String,
    pub first_name: String,
    pub middle_name: Option<String>,
    pub last_name: String,
    pub suffix: Option<String>,
    pub civil_status: String,
    pub gender: String,
    pub nationality: String,
    pub mobile_number: String,
    pub date_of_birth: String,
    pub town_of_birth: String,
    pub province_of_birth: String,
    pub zone: String,
    pub barangay: String,
    pub town: String,
    pub province: String,
    pub father_prefix: String,
    pub father_first_name: String,
    pub father_middle_name: String,
    pub father_last_name: String,
    pub father_suffix: String,
    pub mother_prefix: String,
    pub mother_first_name: String,
    pub mother_middle_name: String,
    pub mother_last_name: String,
    pub status: String,
    pub photo: Option<String>,
    pub is_registered_voter: bool, 
    pub is_pwd: bool,              
    pub is_senior: bool,
}
